# Generated by Django 4.2.29 on 2026-06-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_source_audit_fields'),
        ('mrf', '0005_mrf_commercial_override_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerrequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requests', to='sites.siteprofile'),
        ),
    ]
