# Generated by Django 4.2.29 on 2026-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0006_alter_manpowerrequest_site'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mrflineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('site_role_requirement__isnull', False)), fields=('mrf', 'site_role_requirement'), name='unique_mrf_line_item_per_srr'),
        ),
    ]
