# Generated by Django 4.2.29 on 2026-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='hiring_lane',
            field=models.CharField(choices=[('client_billable', 'Client site manpower'), ('internal_non_billable', 'Internal staff hiring')], db_index=True, default='client_billable', max_length=32),
        ),
    ]
