# Generated by Django 4.2.29 on 2026-06-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_source_audit_fields'),
        ('hiring', '0006_application_match_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringapplication',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='sites.siteprofile'),
        ),
    ]
