# Generated by Django 4.2.29 on 2026-05-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_site_location_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('onboarding_type', models.CharField(choices=[('new_client', 'New Client'), ('new_site_expansion', 'New Site Expansion')], max_length=32)),
                ('expected_site_count', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('operations_notes', models.TextField(blank=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('finance_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_requests', to='sites.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_onboarding_requests', to='core.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_onboarding_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Onboarding Request',
                'verbose_name_plural': 'Client Onboarding Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
