# Generated by Django 4.2.29 on 2026-05-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='budget_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_onboarding_requests', to='budgets.budgetplan'),
        ),
    ]
