# Generated by Django 4.2.29 on 2026-05-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0002_locationarea_minimumwagerate_org_and_more'),
        ('sites', '0004_site_location_area'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0002_add_budget_plan_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingProposedDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_level', models.CharField(choices=[('client', 'Client'), ('site', 'Site')], default='site', max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proposed Department',
                'verbose_name_plural': 'Proposed Departments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOnboardingProposedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('location_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_sites', to='wages.locationarea')),
            ],
            options={
                'verbose_name': 'Proposed Site',
                'verbose_name_plural': 'Proposed Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='created_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_from', to='sites.client'),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='finalization_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='finalization_status',
            field=models.CharField(choices=[('not_finalized', 'Not Finalized'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='not_finalized', max_length=16),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_onboarding_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_client_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientonboardingrequest',
            name='proposed_industry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientonboardingrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_requests', to='sites.client'),
        ),
        migrations.CreateModel(
            name='ClientOnboardingProposedSiteRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_headcount', models.PositiveIntegerField()),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('billing_type', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], default='billable', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_site_requirements', to='jobs.jobrole')),
                ('proposed_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_role_requirements', to='onboarding.clientonboardingproposeddepartment')),
                ('proposed_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_role_requirements', to='onboarding.clientonboardingproposedsite')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_role_requirements', to='onboarding.clientonboardingrequest')),
                ('wage_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_site_requirements', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'Proposed Site Role Requirement',
                'verbose_name_plural': 'Proposed Site Role Requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientonboardingproposedsite',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_sites', to='onboarding.clientonboardingrequest'),
        ),
        migrations.AddField(
            model_name='clientonboardingproposeddepartment',
            name='proposed_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_departments', to='onboarding.clientonboardingproposedsite'),
        ),
        migrations.AddField(
            model_name='clientonboardingproposeddepartment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_departments', to='onboarding.clientonboardingrequest'),
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposedsite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('request', 'code'), name='unique_active_proposed_site_code_per_request'),
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposeddepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('proposed_site__isnull', True)), fields=('request', 'code'), name='unique_active_proposed_dept_client_level'),
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposeddepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('proposed_site__isnull', False)), fields=('request', 'proposed_site', 'code'), name='unique_active_proposed_dept_site_level'),
        ),
    ]
