# Generated by Django 4.2.29 on 2026-05-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_client_onboarding_finalization_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingProposedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=64)),
                ('budget_nature', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], max_length=16)),
                ('budget_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('manpower', 'Manpower'), ('hiring', 'Hiring'), ('operations', 'Operations'), ('deployment', 'Deployment'), ('general', 'General')], default='onboarding', max_length=16)),
                ('scope_level', models.CharField(choices=[('client', 'Client'), ('site', 'Site'), ('department', 'Department')], default='client', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proposed_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_budgets', to='onboarding.clientonboardingproposeddepartment')),
                ('proposed_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_budgets', to='onboarding.clientonboardingproposedsite')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_budgets', to='onboarding.clientonboardingrequest')),
            ],
            options={
                'verbose_name': 'Proposed Budget',
                'verbose_name_plural': 'Proposed Budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposedbudget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('request', 'code'), name='unique_active_proposed_budget_code_per_request'),
        ),
    ]
