# Generated by Django 4.2.29 on 2026-05-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_permission_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0004_client_onboarding_budget_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboardingProposedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('site_manager', 'Site Manager')], default='client', max_length=32)),
                ('scope_level', models.CharField(choices=[('client', 'Client'), ('site', 'Site')], default='client', max_length=16)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('send_invite_on_finalization', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invite_status', models.CharField(choices=[('pending', 'Pending'), ('not_required', 'Not required'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('invite_error', models.TextField(blank=True)),
                ('access_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_proposed_users', to='access.accessrole')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_onboarding_proposals', to=settings.AUTH_USER_MODEL)),
                ('proposed_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_users', to='onboarding.clientonboardingproposedsite')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_users', to='onboarding.clientonboardingrequest')),
            ],
            options={
                'verbose_name': 'Proposed User',
                'verbose_name_plural': 'Proposed Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposeduser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('request', 'email'), name='unique_active_proposed_user_email_per_request'),
        ),
        migrations.AddConstraint(
            model_name='clientonboardingproposeduser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary_contact', True)), fields=('request',), name='unique_primary_proposed_user_per_request'),
        ),
    ]
