# Generated by Django 4.2.29 on 2026-06-16 08:38

from django.db import migrations, models


def backfill_hiring_lane_from_target_role(apps, schema_editor):
    Candidate = apps.get_model('talent', 'Candidate')
    Resume = apps.get_model('talent', 'Resume')
    ResumeImportBatch = apps.get_model('talent', 'ResumeImportBatch')
    JobRole = apps.get_model('jobs', 'JobRole')

    role_lanes = dict(JobRole.objects.values_list('id', 'hiring_lane'))

    for model in (Candidate, Resume, ResumeImportBatch):
        rows = model.objects.filter(
            hiring_lane='',
            target_job_role_id__isnull=False,
        ).only('id', 'target_job_role_id', 'hiring_lane')
        for row in rows.iterator():
            lane = role_lanes.get(row.target_job_role_id)
            if lane:
                model.objects.filter(pk=row.pk).update(hiring_lane=lane)


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_document_type_and_excel_import_history'),
        ('jobs', '0002_jobrole_hiring_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hiring_lane',
            field=models.CharField(blank=True, choices=[('client_billable', 'Client site manpower'), ('internal_non_billable', 'Internal staff hiring')], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resume',
            name='hiring_lane',
            field=models.CharField(blank=True, choices=[('client_billable', 'Client site manpower'), ('internal_non_billable', 'Internal staff hiring')], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='resumeimportbatch',
            name='hiring_lane',
            field=models.CharField(blank=True, choices=[('client_billable', 'Client site manpower'), ('internal_non_billable', 'Internal staff hiring')], db_index=True, default='', max_length=32),
        ),
        migrations.RunPython(backfill_hiring_lane_from_target_role, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['org', 'hiring_lane'], name='talent_cand_org_id_bbb877_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['hiring_lane', 'status'], name='talent_resu_hiring__06c2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeimportbatch',
            index=models.Index(fields=['org', 'hiring_lane'], name='talent_resu_org_id_ad11ed_idx'),
        ),
    ]
